WIP: scripts/run

diff --git a/scripts/run b/scripts/run
--- a/scripts/run
+++ b/scripts/run
@@ -81,13 +81,11 @@ done
 
 echo "logl=${LOG_LEVEL}"
 QUIET="-q"
-VERBOSE_SHELL_ON=""
 if (( ${LOG_LEVEL} >= ${INFO} )); then
 	QUIET=""
 	KPERF_CLIENT_ARGS=""
 fi
 if (( ${LOG_LEVEL} >= ${DEBUG} )); then
-	VERBOSE_SHELL_ON="set -x"
 	KPERF_CLIENT_ARGS="--verbose"
 fi
 
@@ -118,19 +116,11 @@ do_sush2() {
 	shift
 
 	if [[ $# -eq 0 ]]; then
-		COMMAND=$(cat)
+		sush2 --reason 'network testing with kperf' -q -t root@${host} "$(cat)"
 	else
-		COMMAND="$*"
+		sush2 --reason 'network testing with kperf' -q -t root@${host} "$*"
 	fi
-
-		sush2 --reason 'network testing with kperf' -q -t root@${host} <<EOF
-	set -e
-	(
-		set -e
-		${VERBOSE_SHELL_ON}
-		${COMMAND}
-	)
-EOF
+	return $?
 }
 
 query_ip() {
@@ -146,20 +136,6 @@ __setup_flow_control() {
 	else
 		local NICS=("${SRC_NICS[@]}")
 		local host=${SOURCE}
-	fi
-
-	if (( ${LOG_LEVEL} >= ${DEBUG} )); then
-		local TMP=$(mktemp)
-		echo "${host}: NIC Setup Before:"
-		do_sush2 ${host} > ${TMP}  <<-EOF
-			for nic in ${NICS[*]}; do
-				ethtool -l \$nic
-				ethtool -x \$nic
-			done
-		EOF
-
-		cat ${TMP} | awk '{ printf "'"$host"': "; print $0; }'
-		rm ${TMP}
 	fi
 
 	do_sush2 ${host} <<-EOF
@@ -191,27 +167,12 @@ __setup_flow_control() {
 			ethtool -C \$nic rx-usecs $2 rx-frames $3 tx-usecs $4 tx-frames $5
 		done
 	EOF
-
-	if (( ${LOG_LEVEL} >= ${DEBUG} )); then
-		local TMP=$(mktemp)
-		echo "${host}: NIC Setup Before:"
-		do_sush2 ${host} > ${TMP}  <<-EOF
-			for nic in ${NICS[*]}; do
-				ethtool -l \$nic
-				ethtool -x \$nic
-			done
-		EOF
-
-		cat ${TMP} | awk '{ printf "'"$host"': "; print $0; }'
-		rm ${TMP}
-	fi
 }
 
 setup_flow_control() {
 	local DEFAULT_COAL="3 32 16 32" # 400G
 	__setup_flow_control 1 $DEFAULT_COAL
 	__setup_flow_control 0 $DEFAULT_COAL
-	exit
 }
 
 declare -A SRC_IPS
@@ -289,13 +250,14 @@ copy_kperf() {
 }
 
 kill_kperf_servers() {
-	do_sush2 ${SOURCE} 'LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-12.4/targets/x86_64-linux/lib ./server --kill'
-	do_sush2 ${DESTINATION} 'LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-12.4/targets/x86_64-linux/lib ./server --kill'
+	do_sush2 ${SOURCE} 'LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-12.4/targets/x86_64-linux/lib ./server --kill --pid-file /tmp/kperf.src.pid'
+	do_sush2 ${DESTINATION} 'LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-12.4/targets/x86_64-linux/lib ./server --kill --pid-file /tmp/kperf.dst.pid'
 }
 
 spawn_kperf_servers() {
-	do_sush2 ${SOURCE} 'LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-12.4/targets/x86_64-linux/lib nohup ./server --verbose > ./kperf.src.log'
-	do_sush2 ${DESTINATION} 'LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-12.4/targets/x86_64-linux/lib nohup ./server --verbose > ./kperf.dst.log'
+	echo "Spawning kperf servers..."
+	do_sush2 ${SOURCE} 'LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-12.4/targets/x86_64-linux/lib nohup ./server --verbose --pid-file /tmp/kperf.src.pid 2>&1 > ./kperf.src.log'
+	do_sush2 ${DESTINATION} 'LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-12.4/targets/x86_64-linux/lib nohup ./server --verbose --pid-file /tmp/kperf.dst.pid 2>&1 > ./kperf.dst.log'
 }
 
 run_kperf_client() {
@@ -312,43 +274,57 @@ run_kperf_client() {
 	sush2 --reason "networking testing with kperf" root@${SOURCE} -- ${COMMAND}
 }
 
+numa_lookup() {
+	for node in /sys/devices/system/node/node*; do
+		echo
+	done
+}
+
 set_nic_smp_affinity() {
 	local host=$1
 	local device=$2
+	local mode=$3
 
-	do_sush2 ${host} <<-EOF
-		cpulist=\$(cat /sys/class/net/${device}/device/local_cpulist)
-		segments=\$(echo \$cpulist | tr -cd ',' | wc -c)
-		segments=\$(( segments + 1 ))
+	if [[ "${mode}" == 1to1 ]]; then
+		do_sush2 ${host} <<-EOF
+			cpulist=\$(cat /sys/class/net/${device}/device/local_cpulist)
+			segments=\$(echo \$cpulist | tr -cd ',' | wc -c)
+			segments=\$(( segments + 1 ))
 
-		irqs=()
-		irqs_len=0
-		for irq in \$(ls /sys/class/net/${device}/device/msi_irqs); do
-			irqs+=(\${irq})
-			irqs_len=\$(( irqs_len + 1 ))
-		done
+			irqs=()
+			irqs_len=0
+			for irq in \$(ls /sys/class/net/${device}/device/msi_irqs); do
+				irqs+=(\${irq})
+				irqs_len=\$(( irqs_len + 1 ))
+			done
 
-#		cpus=()
-#		for ((i = 0; i < segments; i++)); do
-#			range=\$(echo \${cpulist} | cut -d ',' -f \$(( i + 1 )) )
-#			lo="\$(echo \${range} | cut -d '-' -f1)"
-#			hi="\$(echo \${range} | cut -d '-' -f2)"
-#
-#			for ((cpu = lo; cpu <= hi; cpu++)); do
-#				cpus+=(\${cpu})
-#			done
-#		done
+			cpus=()
+			for ((i = 0; i < segments; i++)); do
+				range=\$(echo \${cpulist} | cut -d ',' -f \$(( i + 1 )) )
+				lo="\$(echo \${range} | cut -d '-' -f1)"
+				hi="\$(echo \${range} | cut -d '-' -f2)"
 
-		i=0
-		j=0
+				for ((cpu = lo; cpu <= hi; cpu++)); do
+					cpus+=(\${cpu})
+				done
+			done
 
-		while [[ \${i} -lt \${irqs_len} ]]; do
-			irq=\${irqs[\${i}]}
-			echo "\${cpulist}" > /proc/irq/\${irq}/smp_affinity_list
-			i=\$(( i + 1 ))
-			j=\$(( j + 1 ))
-		done
+			i=0
+			while [[ \${i} -lt \${irqs_len} ]]; do
+				irq=\${irqs[\${i}]}
+				echo "\${cpus[\$i]}" > /proc/irq/\${irq}/smp_affinity_list
+				i=\$(( i + 1 ))
+			done
 	EOF
+	elif [[ "${mode}"k != "spread" ]]; then
+		do_sush2 ${host} <<-EOF
+			for irq in \$(ls /sys/class/net/${device}/device/msi_irqs); do
+				cat /sys/class/net/${device}/device/local_cpulist > /proc/irq/\${irq}/smp_affinity_list
+			done
+		EOF
+	else
+		die "Invalid affinity mode: ${mode}"
+	fi
 }
 
 # Build
@@ -356,20 +332,73 @@ make clean && make -j$(nproc) USE_CUDA=1
 
 collect_ips
 setup_flow_control
+echo "Adding IP routes..."
 add_routes $SOURCE
 add_routes $DESTINATION
 
-#for nic in ${SRC_NICS[@]}; do
-#	set_nic_smp_affinity $SOURCE ${nic}
-#done
+echo "IP routes:"
+if (( ${LOG_LEVEL} >= ${DEBUG} )); then
+	for nic in ${SRC_NICS[@]}; do
+		do_sush2 $SOURCE ip addr show ${nic}
+		do_sush2 $SOURCE ip -6 route show dev ${nic}
+	done | awk -v host=${SOURCE} '{printf "%s:\t", host; print }'
 
-#for nic in ${DST_NICS[@]}; do
-#	set_nic_smp_affinity $DESTINATION ${nic}
-#done
+	for nic in ${DST_NICS[@]}; do
+		do_sush2 $DESTINATION ip addr show ${nic}
+		do_sush2 $DESTINATION ip -6 route show dev ${nic}
+	done | awk -v host=${DESTINATION} '{printf "%s:\t", host; print }'
+fi
+
+for nic in ${SRC_NICS[@]}; do
+	set_nic_smp_affinity $SOURCE ${nic} 1to1
+done
+
+for nic in ${DST_NICS[@]}; do
+	set_nic_smp_affinity $DESTINATION ${nic} 1to1
+done
+
+if (( ${LOG_LEVEL} >= ${DEBUG} )); then
+	TMP=$(mktemp)
+	echo "${SOURCE}: NIC Setup:"
+	do_sush2 ${SOURCE} > ${TMP} <<-EOF
+		for nic in ${SRC_NICS[@]}; do
+			echo "NIC: \$nic"
+			ethtool -l \$nic
+			ethtool -x \$nic
+			for irq in \$(ls /sys/class/net/\${nic}/device/msi_irqs); do
+				echo -e "\t\${nic} (node \$(cat /sys/class/net/\${nic}/device/numa_node)) IRQ \${irq} -> CPU (s) \$(cat /proc/irq/\${irq}/smp_affinity_list)"
+			done | awk '{ printf "\t"; print }'
+		done
+	EOF
+	cat ${TMP} | awk '{ printf "'"${SOURCE}"': "; print; }'
+
+	> ${TMP}
+	echo "${DESTINATION}: NIC Setup:"
+	do_sush2 ${DESTINATION} > ${TMP} <<-EOF
+	for nic in ${DST_NICS[@]}; do
+			echo "NIC: \$nic"
+			ethtool -l \$nic | awk '{ printf '\t'; print }'
+			ethtool -x \$nic | awk '{ printf '\t'; print }'
+			for irq in \$(ls /sys/class/net/\${nic}/device/msi_irqs); do
+				echo -e "\t\${nic} (node \$(cat /sys/class/net/\${nic}/device/numa_node)) IRQ \${irq} -> CPU (s) \$(cat /proc/irq/\${irq}/smp_affinity_list)"
+			done | awk '{ printf "\t"; print }'
+		done
+	EOF
+	cat ${TMP} | awk '{ printf "'"${DESTINATION}"': "; print; }'
+	rm ${TMP}
+fi
 
 kill_kperf_servers
 copy_kperf
 spawn_kperf_servers
+set -x
+echo "Spawned..."
+while ! do_sush2 ${DESTINATION} test -e /tmp/kperf.dst.pid; do
+	sleep 1
+done
+while ! do_sush2 ${SOURCE} test -e /tmp/kperf.src.pid; do
+	sleep 1
+done
 run_kperf_client							\
 	${KPERF_CLIENT_ARGS}				\
 #	--devmem-rx									\
